<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="YP_Automation"
           tests="5"
           failures="1"
           errors="0"
           skipped="0"
           time="507.199">
  <properties />
            <testcase name="fblogin" time="28.642" classname="com.yp.testscripts.YapyzalTestSuite">
                <failure type="junit.framework.AssertionFailedError"
                  message="FindFailed: can not find E:\Yapyzal\sikuli\block.PNG on the screen.
  Line 1574, in file Region.java
"
              >
<![CDATA[junit.framework.AssertionFailedError: FindFailed: can not find E:\Yapyzal\sikuli\block.PNG on the screen.
  Line 1574, in file Region.java

  junit.framework.Assert.fail(Assert.java:50)
  com.yp.pagefactory.FbLogin.accountlogin(FbLogin.java:46)
  com.yp.testscripts.YapyzalTestSuite.fblogin(YapyzalTestSuite.java:71)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:497)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="Deal" time="192.732" classname="com.yp.testscripts.YapyzalTestSuite" />
                <testcase name="Login" time="22.682" classname="com.yp.testscripts.YapyzalTestSuite" />
                <testcase name="DonateStatic" time="131.786" classname="com.yp.testscripts.YapyzalTestSuite" />
                <testcase name="DonateDynamic" time="131.357" classname="com.yp.testscripts.YapyzalTestSuite" />
      
</testsuite>
